apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: high-availability-application
  annotations:
    openshift.io/display-name: "High Availability Application"
    description: "This template deploys application by creating all the relevant objects in high availability architecture that is defined by OpenShift team"
    openshift.io/provider-display-name: "IDFCTS"
    iconClass: "icon-openshift"
    tags: "application,nodejs,python,java"
    openshift.io/support-url: "https://support.idf.cts"
message: "Successfully deployed!"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${name}-deployment
  spec:
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    replicas: 3
    selector:
      matchLabels:
        app: ${name}-template
    template:
      metadata:
        labels:
          app: ${name}-template
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ${name}-template
              topologyKey: failure-domain.beta.kubernetes.io/zone
        containers:
        - name: ${name}-pod
          image: ${image}
          ports:
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: ${name}-service
  spec:
    type: ClusterIP
    selector:                  
      app: ${name}-template
    ports:
    - port: 8080
      targetPort: 8080
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${name}-route
  spec:
    host: debug.openshift.cts
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${name}-service
parameters:
  - name: name
    description: Application Name
    required: true
  - name: image
    description: Container Image
    required: true
  - name: port
    description: Container Listening Port
    required: true
  - name: DNS
    description: Route DNS Address
    required: true
