apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.applicationName}}-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.applicationName}}-template
  template:
    metadata:
      labels:
        app: {{.Values.applicationName}}-template
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
        topologyKey: failure-domain.beta.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app: {{.Values.applicationName}}-template
      containers:
      - name: {{.Values.applicationName}}-pod
        image: {{.Values.image.name}}:{{.Values.image.tag}}
        ports:
        - containerPort: {{.Values.network.containerPort}}
        resources:
          requests:
            memory: {{.Values.resources.requestedMemory}}Mi
            cpu: {{.Values.resources.requestedCpu}}m
          limits:
            memory: {{.Values.resources.memoryLimit}}Mi
            cpu: {{.Values.resources.cpuLimit}}m
