apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Values.applicationName}}-route
spec:
  host: {{.Values.network.externalDns}}
  port:
    targetPort: {{.Values.network.containerPort}}
  to:
    kind: Service
    name: {{.Values.applicationName}}-service
