apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Values.name}}-route
spec:
  host: debug.openshift.cts
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{.Values.name}}-service
