applicationName: ''
image:
  name: ''
  tag: ''
network:
  containerPort: ''
  servicePort: '' 
  externalDns: ''
resources:
  requestedMemory: 100
  requestedCpu: 100
  memoryLimit: 200
  cpuLimit: 200
